config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products', as: :products
  get '/solucoes' => 'static_pages#solutions', as: :solutions
  get '/sobre-nos' => 'static_pages#about_us', as: :about_us
  get '/conteudos' => 'static_pages#content', as: :content
  get '/contato' => 'static_pages#contact'

  get '/solucoes/big-data' => 'solutions#big_data', as: :big_data
  get '/solucoes/business-intelligence-analytics' => 'solutions#bi_analytics', as: :bi_analytics
  get '/solucoes/oncase-labs' => 'solutions#oncase_labs', as: :oncase_labs
  get '/solucoes/inteligencia-artificial' => 'solutions#inteligencia_artificial', as: :inteligencia_artificial

  get '/tecnologias/pentaho' => 'technologies#pentaho', as: :pentaho
  get '/tecnologias/cloudera' => 'technologies#cloudera', as: :cloudera
  get '/tecnologias/mongodb' => 'technologies#mongodb', as: :mongodb

  get '/pages/:slug' => 'pages#show', as: :page

  namespace :admin do
    resources :pages do
      resources :text_contents
      resources :image_contents
      resources :link_contents
    end

    resources :products
    resources :solutions
  end

  get 'subscribers/export' => 'subscribers#export', as: :export_subscribers

  resources :subscribers, only: [:create]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @home = Page.find_by_slug('home')
    @texto_1 = @home.text_contents.find_by_slug('texto-1')
  end

  def products
    @products = Product.all.order(position: :asc)
    @products_page = Page.find_by_slug('produtos')

    @text_contents = @products_page.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
  end

  def solutions
    @solutions = Solution.all.order(position: :asc)
    @solutions_page = Page.find_by_slug('solucoes')

    @text_contents = @solutions_page.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
  end

  def content
    @content = Page.find_by_slug('conteudo')

    @video = @content.link_contents.first
  end

  def about_us
    @about_us = Page.find_by_slug('sobre-nos')

    @video = @about_us.link_contents.first
    @link = @about_us.link_contents.last

    @text_contents = @about_us.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
    @texto_2 = @text_contents.find_by_slug('texto-2')
    @texto_3 = @text_contents.find_by_slug('texto-3')
    
    @image_contents = @about_us.image_contents
    @imagem_1 = @image_contents.find_by_slug('imagem-1')
    @imagem_2 = @image_contents.find_by_slug('imagem-2')
    @imagem_3 = @image_contents.find_by_slug('imagem-3')
  end

  def contact
  end
end

app/views/static_pages/about_us.html.erb
<% content_for :title, "Oncase | Experts em Big Data, Analytics e Inteligência artificial" %>

<% if user_signed_in? and notice %>
  <div class="alert alert-success mb-0">
    <div class="container">
      <span>Tudo certo!</span> <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="about-us">
  <div class="content container">
    <div class="title">
      SOBRE NÓS
    </div>

    <!-- first section -->
    <div class="d-flex first-section">
      <div class="text-content">
        <%= markdown(@texto_1.content) %>

        <% if user_signed_in? %>
          <%= link_to 'editar texto',
              edit_admin_page_text_content_path(@about_us, @texto_1),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>
      </div>

      <div class="video">
        <iframe width="500px" height="350px" src="<%= @video.href %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        
        <% if user_signed_in? %>
          <%= link_to 'editar video',
              edit_admin_page_link_content_path(@about_us, @video),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>
      </div>
    </div>

    <!-- second section -->
    <div class="d-flex second-section" id="our-history">
      <div class="image-content">
        <%= cl_image_tag "#{@imagem_2.image.path}",
            style: "width: auto;
                    height: #{@imagem_2.height}px;
                    margin-left: #{@imagem_2.margin_left}em;
                    margin-right: #{@imagem_2.margin_right}em;", title: "#{@imagem_2.title}"%>

          <% if user_signed_in? %>
            <div class="text-center pt-4">
              <%= link_to 'editar imagem',
                  edit_admin_page_image_content_path(@about_us, @imagem_2),
                  class: 'btn btn-sm btn-outline-info',
                  remote: true %>
            </div>
          <% end %>
      </div>

      <div class="text-content">
        <%= markdown(@texto_2.content) %>

        <% if user_signed_in? %>
          <%= link_to 'editar texto',
              edit_admin_page_text_content_path(@about_us, @texto_2),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- a company -->
  <div class="company text-center pt-4 mb-4">
    <h1 class="title m-0">Uma empresa:</h1>

    <div class="d-flex justify-content-center pt-5 mt-2 pb-2">
      <%= image_tag 'novo/about-us/criatec.png', class: 'company-image' %>
      <break></break>
      <%= image_tag 'novo/about-us/porto-digital.png', class: 'company-image' %>
      <break></break>
      <%= image_tag 'novo/about-us/manguez-al.png', class: 'company-image' %>
    </div>
  </div>

  <!-- partners -->
  <%= image_tag 'bg-tech@2x.png', width: '100%' %>

  <div class="partners text-center">
    <h1 class="title m-0">Parceiros Oficiais</h1>

    <div class="d-flex justify-content-center pt-4 pb-2">
      <%= image_tag 'tecnologias/pentaho.png', class: 'partner-image' %>
      <break></break>
      <%= image_tag 'tecnologias/cloudera.png', class: 'partner-image' %>
      <break></break>
      <%= image_tag 'tecnologias/mongodb.png', class: 'partner-image' %>
    </div>
  </div>

  <%= image_tag 'bg-cta.png', width: '100%', style: 'margin-top: -1px;' %>

  <!-- our team -->
  <div class="content container" id="our-team">
    <div class="d-flex our-team">
      <div class="image-content">
        <%= cl_image_tag "#{@imagem_3.image.path}",
            style: "width: auto;
                    height: #{@imagem_3.height}px;
                    margin-left: #{@imagem_3.margin_left}em;
                    margin-right: #{@imagem_3.margin_right}em;", title: "#{@imagem_3.title}"%>

          <% if user_signed_in? %>
            <div class="text-center pt-4">
              <%= link_to 'editar imagem',
                  edit_admin_page_image_content_path(@about_us, @imagem_3),
                  class: 'btn btn-sm btn-outline-info',
                  remote: true %>
            </div>
          <% end %>
      </div>

      <div class="text-content">
        <%= markdown(@texto_3.content) %>

        <% if user_signed_in? %>
          <%= link_to 'editar texto',
              edit_admin_page_text_content_path(@about_us, @texto_3),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>

        <div class="d-flex gptw pt-4">
          <%= image_tag 'selo-gptw.png', height: '130px' %>
          <break></break>
          <div class="align-self-center job-button">
            <%= link_to @link.name, @link.href, class: 'btn btn-outline-orange' %>
          </div>
        </div>

        <% if user_signed_in? %>
          <%= link_to 'editar link',
              edit_admin_page_link_content_path(@about_us, @link),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% content_for :title, "Oncase | Experts em Big Data, Analytics e Inteligência artificial" %>

<div class="contact pb-5">
  <div class="content container">
    <div class="title">
      CONTATO
    </div>

    <div class="description">
      Mande a sua mensagem para a Oncase, o nosso time responderá o mais rápido possível.
    </div>

    <div class="talk">
      <div class="row">
        <div class="col-md-4">
          <form action="https://formspree.io/contato@oncase.com.br" method="POST">
            <div class="form-group">
              <label for="nome">Como podemos chamar você?</label>
              <input type="text" name="nome" class="form-control" placeholder="Pode ser o seu primeiro nome...">
            </div>

            <div class="form-group">
              <label for="email">Seu email:</label>
              <input type="email" name="email" class="form-control" placeholder="seu@email.com">
            </div>

            <div class="form-group">
              <label for="mensagem">Escreva uma mensagem para a gente:</label>
              <textarea name="mensagem" class="form-control" placeholder="Sua mensagem..." rows="5"></textarea>
            </div>

            <button type="submit" class="btn btn-light-blue">Enviar <strong>Mensagem</strong></button>
          </form>
        </div>

        <div class="col-md-2"></div>

        <div class="col-md-4">
          <div class="place">
            <div class="title">
              <strong>Recife</strong>
            </div>

            <div class="d-flex address align-items-start pt-3">
              <%= image_tag "icone-mapa@2x.png" %>
              <div class="pl-3">
                Rua do Bom Jesus, 163
                <br>
                2 andar - Recife-PE 
                <br>
                CEP 50.030-170 
              </div>
            </div>

            <div class="d-flex phone align-items-start pt-2">
              <%= image_tag "icone-telefone@2x.png" %>
              <div class="pl-3">
                Fone: +55-81-3077-8558
              </div>
            </div>
          </div>

          <div class="place pt-5">
            <div class="title">
              <strong>São Paulo</strong>
            </div>

            <div class="d-flex phone align-items-start pt-3">
              <%= image_tag "icone-telefone@2x.png" %>
              <div class="pl-3">
                Fone: +55-11-4118-3068
              </div>
            </div>
          </div>

          <div class="social">
            <div class="medias">
              <a href="https://www.facebook.com/oncasesolucoes/" target="_blank" class="link">
                <%= fa_icon 'facebook' %>
              </a>

              <a href="https://www.linkedin.com/company/oncase/" target="_blank" class="link">
                <%= fa_icon 'linkedin' %>
              </a>

              <a href="https://twitter.com/oncase" target="_blank" class="link">
                <%= fa_icon 'twitter' %>
              </a>

              <a href="https://www.youtube.com/channel/UC4sU9JSX8n7rD2tcBgJkjFQ" target="_blank" class="link">
                <%= fa_icon 'youtube-play' %>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/content.html.erb
<% content_for :title, "Oncase | Experts em Big Data, Analytics e Inteligência artificial" %>

<div class="content-page">
  <div class="content container">
    <div class="title">CONTEÚDO</div>

    <div class="description">
      Nossos conteúdos já ajudaram centenas de empresas a atingirem seus objetivos através de uma melhor estratégia de dados. <strong>Nós queremos ajudar você também!</strong>
    </div>

    <div class="content-box">
      <div class="d-flex align-items-start">
        <div class="text pr-5">
          <div class="title">Blog</div>

          <div class="description">
            Conteúdos diários atualizado com boas práticas e novidades no mundo de Big Data, Analytics e Data Science.
          </div>

          <a href="http://blog.oncase.com.br/" target="_blank" class="btn btn-outline-light-blue mt-4">
            Conheça o nosso <strong>Blog</strong>
            <span>&nbsp;</span>
            <%= fa_icon 'chevron-right' %>
          </a>
        </div>

        <%= image_tag "blog@2x.png" %>
      </div>
    </div>

    <div class="content-box reverse">
      <div class="d-flex align-items-start">
        <%= image_tag "insights@2x.png", class: "pr-5" %>

        <div class="text pl-5">
          <div class="title">Oncase Insights</div>

          <div class="description">
            O Oncase Insights é uma central pesquisa e análise direta da nossa equipe. Reunimos dados de diversos lugares, tudo para explorar as complexidades relacionada a dados do cotidiano de tecnologia.
          </div>

          <a href="https://medium.com/oncase" target="_blank" class="btn btn-outline-orange mt-4">
            Conheça o <strong>Oncase Insights</strong>
            <span>&nbsp;</span>
            <%= fa_icon 'chevron-right' %>
          </a>
        </div>
      </div>
    </div>

    <div class="content-box reverse">
      <div class="d-flex align-items-start">
        <div class="text pr-5">
          <div class="title">Oncase TV</div>

          <div class="description">
            O maior canal brasileiro de Big Data & Analytics! Toda semana um conteúdo novo falando sobre as principais novidades do mercado e dúvidas frequentes.
          </div>

          <div class="pt-4">
            <iframe width="400px" height="250px" src="<%= @video.href %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

            <% if user_signed_in? %>
              <%= link_to 'editar video',
                  edit_admin_page_link_content_path(@content, @video),
                  class: 'btn btn-sm btn-outline-info',
                  remote: true %>
            <% end %>
          </div>

          <a href="https://www.youtube.com/c/OncaseBr" target="_blank" class="btn btn-outline-red mt-4">
            Veja mais vídeos no nosso <strong>Canal</strong>
            <span>&nbsp;</span>
            <%= fa_icon 'chevron-right' %>
          </a>
        </div>

        <%= image_tag "tv@2x.png", height: "150px", class: "pl-5" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% content_for :title, "Oncase | Experts em Big Data, Analytics e Inteligência artificial" %>

<div class="d-none d-md-block">
  <div class="home">
    <div class="phrase-wrapper d-flex justify-content-center align-items-center">
      <div class="phrase">
        <%= markdown(@texto_1.content) %>

        <% if user_signed_in? %>
          <%= link_to 'editar texto',
              edit_admin_page_text_content_path(@home, @texto_1),
              class: 'btn btn-sm btn-outline-info',
              remote: true %>
        <% end %>
        
        <div class="buttons pt-5 mt-2">
          <%= link_to 'Produtos', products_path, class: 'btn btn-outline-orange btn-lg' %>
          <span>&nbsp;</span>
          <%= link_to 'Soluções', solutions_path, class: 'btn btn-outline-orange btn-lg' %>
        </div>
      </div>
    </div>
    <div id="particles">
    </div>
  </div>
</div>

<div class="d-block d-md-none">
  <div class="home-mobile">
    <div class="phrase-wrapper">
      <div class="phrase">
        <%= markdown(@texto_1.content) %>
      </div>

      <div class="buttons mt-5">
        <%= link_to 'Produtos', products_path, class: 'btn btn-outline-orange' %>
        <span>&nbsp;</span>
        <%= link_to 'Soluções', solutions_path, class: 'btn btn-outline-orange' %>
      </div>
    </div>

    <div id="particles-mobile">
    </div>
  </div>
</div>

<script>
  $(document).on("turbolinks:load", function () {
    particlesJS('particles',
      {
        "particles": {
          "canvas": {
            "width": "500px",
            "height": "500px"
          },
          "number": {
            "value": 80,
            "density": {
              "enable": true,
              "value_area": 800
            }
          },
          "color": {
            "value": "#dcdcdc"
          },
          "shape": {
            "type": "circle",
            "stroke": {
              "width": 0,
              "color": "#000000"
            },
            "polygon": {
              "nb_sides": 5
            },
            "image": {
              "src": "img/github.svg",
              "width": 100,
              "height": 100
            }
          },
          "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {
              "enable": false,
              "speed": 1,
              "opacity_min": 0.1,
              "sync": false
            }
          },
          "size": {
            "value": 5,
            "random": true,
            "anim": {
              "enable": false,
              "speed": 40,
              "size_min": 0.1,
              "sync": false
            }
          },
          "line_linked": {
            "enable": true,
            "distance": 150,
            "color": "#333133",
            "opacity": 0.4,
            "width": 1
          },
          "move": {
            "enable": true,
            "speed": 6,
            "direction": "none",
            "random": false,
            "straight": false,
            "out_mode": "out",
            "attract": {
              "enable": false,
              "rotateX": 600,
              "rotateY": 1200
            }
          }
        },
        "interactivity": {
          "detect_on": "canvas",
          "events": {
            "onhover": {
              "enable": false,
              "mode": "repulse"
            },
            "onclick": {
              "enable": true,
              "mode": "push"
            },
            "resize": true
          },
          "modes": {
            "grab": {
              "distance": 400,
              "line_linked": {
                "opacity": 1
              }
            },
            "bubble": {
              "distance": 400,
              "size": 40,
              "duration": 2,
              "opacity": 8,
              "speed": 3
            },
            "repulse": {
              "distance": 200
            },
            "push": {
              "particles_nb": 4
            },
            "remove": {
              "particles_nb": 2
            }
          }
        },
        "retina_detect": true,
        "config_demo": {
          "hide_card": false,
          "background_color": "#b61924",
          "background_image": "",
          "background_position": "30% 50%",
          "background_repeat": "no-repeat",
          "background_size": "cover"
        }
      }
    );

    particlesJS('particles-mobile',
      {
        "particles": {
          "canvas": {
            "width": "500px",
            "height": "500px"
          },
          "number": {
            "value": 80,
            "density": {
              "enable": true,
              "value_area": 800
            }
          },
          "color": {
            "value": "#dcdcdc"
          },
          "shape": {
            "type": "circle",
            "stroke": {
              "width": 0,
              "color": "#000000"
            },
            "polygon": {
              "nb_sides": 5
            },
            "image": {
              "src": "img/github.svg",
              "width": 100,
              "height": 100
            }
          },
          "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {
              "enable": false,
              "speed": 1,
              "opacity_min": 0.1,
              "sync": false
            }
          },
          "size": {
            "value": 5,
            "random": true,
            "anim": {
              "enable": false,
              "speed": 40,
              "size_min": 0.1,
              "sync": false
            }
          },
          "line_linked": {
            "enable": true,
            "distance": 150,
            "color": "#333133",
            "opacity": 0.4,
            "width": 1
          },
          "move": {
            "enable": true,
            "speed": 6,
            "direction": "none",
            "random": false,
            "straight": false,
            "out_mode": "out",
            "attract": {
              "enable": false,
              "rotateX": 600,
              "rotateY": 1200
            }
          }
        },
        "interactivity": {
          "detect_on": "canvas",
          "events": {
            "onhover": {
              "enable": false,
              "mode": "repulse"
            },
            "onclick": {
              "enable": true,
              "mode": "push"
            },
            "resize": true
          },
          "modes": {
            "grab": {
              "distance": 400,
              "line_linked": {
                "opacity": 1
              }
            },
            "bubble": {
              "distance": 400,
              "size": 40,
              "duration": 2,
              "opacity": 8,
              "speed": 3
            },
            "repulse": {
              "distance": 200
            },
            "push": {
              "particles_nb": 4
            },
            "remove": {
              "particles_nb": 2
            }
          }
        },
        "retina_detect": true,
        "config_demo": {
          "hide_card": false,
          "background_color": "#b61924",
          "background_image": "",
          "background_position": "30% 50%",
          "background_repeat": "no-repeat",
          "background_size": "cover"
        }
      }
    );
  });
</script>

app/views/static_pages/products.html.erb
<% content_for :title, "Produtos | Experts em Big Data, Analytics e Inteligência artificial" %>

<% if user_signed_in? and notice %>
  <div class="alert alert-success mb-0">
    <div class="container">
      <span>Tudo certo!</span> <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="products container">
  <div class="title">
    PRODUTOS
  </div>

  <div class="description text-content pt-4">
    <%= markdown(@texto_1.content) %>

      <% if user_signed_in? %>
        <%= link_to 'editar texto',
            edit_admin_page_text_content_path(@products_page, @texto_1),
            class: 'btn btn-sm btn-outline-info',
            remote: true %>
      <% end %>
  </div>

  <div class="list mt-5 pt-5">
    <div class="row pt-5">
      <% @products.each do |product| %>
        <div class="product col-md-6 pb-5 mb-5">
          <% if product.logo.present? %>
            <%= cl_image_tag product.logo.path, height: "#{product.image_height}px" %>
          <% end %>

          <div class="text-content description pt-4">
            <% if product.description %>
              <%= markdown(product.description) %>
            <% end %>
          </div>

          <a href="<%= product.href %>" class="btn btn-outline-primary" target="_blank">
            Veja mais sobre o <strong><%= product.name %></strong>
            <span>&nbsp;</span>
            <%= fa_icon "chevron-right" %>
          </a>

          
          <% if user_signed_in? %>
            <%= link_to 'editar produto',
                edit_admin_product_path(product),
                class: 'btn btn-sm btn-outline-info',
                target: '_blank' %>
          <% end %>
          
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/solutions.html.erb
<% content_for :title, "Soluções | Experts em Big Data, Analytics e Inteligência artificial" %>

<% if user_signed_in? and notice %>
  <div class="alert alert-success mb-0">
    <div class="container">
      <span>Tudo certo!</span> <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="products container">
  <div class="title">
    SOLUÇÕES
  </div>

  <div class="description text-content pt-4">
    <%= markdown(@texto_1.content) %>

      <% if user_signed_in? %>
        <%= link_to 'editar texto',
            edit_admin_page_text_content_path(@solutions_page, @texto_1),
            class: 'btn btn-sm btn-outline-info',
            remote: true %>
      <% end %>
  </div>

  <div class="list mt-5 pt-5">
    <div class="row pt-5">
      <% @solutions.each do |solution| %>
        <div class="product col-md-6 pb-5 mb-5">
          <% if solution.logo.present? %>
            <%= cl_image_tag solution.logo.path, height: "#{solution.image_height}px" %>
          <% end %>

          <div class="text-content description pt-4">
            <% if solution.description %>
              <%= markdown(solution.description) %>
            <% end %>
          </div>

          <a href="<%= solution.href %>" class="btn btn-outline-primary" target="_blank">
            Veja mais sobre <strong><%= solution.name %></strong>
            <span>&nbsp;</span>
            <%= fa_icon "chevron-right" %>
          </a>

          <% if user_signed_in? %>
            <%= link_to 'editar solução',
                edit_admin_solution_path(solution),
                class: 'btn btn-sm btn-outline-info',
                target: '_blank' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>