config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products', as: :products
  get '/solucoes' => 'static_pages#solutions', as: :solutions
  get '/sobre-nos' => 'static_pages#about_us', as: :about_us
  get '/conteudos' => 'static_pages#content', as: :content
  get '/contato' => 'static_pages#contact'

  get '/solucoes/big-data' => 'solutions#big_data', as: :big_data
  get '/solucoes/business-intelligence-analytics' => 'solutions#bi_analytics', as: :bi_analytics
  get '/solucoes/oncase-labs' => 'solutions#oncase_labs', as: :oncase_labs
  get '/solucoes/inteligencia-artificial' => 'solutions#inteligencia_artificial', as: :inteligencia_artificial

  get '/tecnologias/pentaho' => 'technologies#pentaho', as: :pentaho
  get '/tecnologias/cloudera' => 'technologies#cloudera', as: :cloudera
  get '/tecnologias/mongodb' => 'technologies#mongodb', as: :mongodb

  get '/pages/:slug' => 'pages#show', as: :page

  namespace :admin do
    resources :pages do
      resources :text_contents
      resources :image_contents
      resources :link_contents
    end

    resources :products
    resources :solutions
  end

  get 'subscribers/export' => 'subscribers#export', as: :export_subscribers

  resources :subscribers, only: [:create]
end

app/models/product.rb
class Product < ApplicationRecord
  has_attachment :logo, accept: [:jpg, :png, :gif]
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    before_action :set_product, only: [:edit, :update, :destroy]

    def index
      @products = Product.all.order(position: :asc)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_path, notice: 'O produto foi criado com sucesso!' }
        else
          format.html { render 'new' }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @product.update_attributes(product_params)
          format.html { redirect_to admin_products_path, notice: 'O produto foi atualizado com sucesso!' }
        else
          format.html { render 'new' }
        end
      end
    end

    def destroy
      respond_to do |format|
        if @product.destroy
          format.html { redirect_to admin_products_path, notice: 'O produto foi excluído com sucesso!' }
        end
      end 
    end

    private

      def set_product
        @product = Product.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:name, :description, :logo, :image_height, :position, :href)
      end
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :position, 'Posição na exibição' %>
        <%= f.number_field :position, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :href, 'Link' %>
        <%= f.text_field :href, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :description, 'Descrição' %>
        <%= f.text_area :description %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-body">
          <div class="form-group">
            <%= f.label :logo %>
            <br>
            <%= f.attachinary_file_field :logo, required: true %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :image_height, 'Altura da logo' %>
        <%= f.number_field :image_height, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="actions pt-2">
    <%= f.submit 'Salvar produto', class: 'btn btn-success' %>
    <span>&nbsp;</span>
    <%= link_to 'Cancelar', admin_products_path, class: 'btn btn-outline-danger' %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    var simplemde = new SimpleMDE();
  });
</script>

app/views/admin/products/edit.html.erb
<div class="container pt-4">
  <div class="d-flex">
    <h1>Editar produto</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <%= render 'form' %>
</div>

app/views/admin/products/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <div class="container">
      Tudo certo! <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="container pt-4">
  <div class="d-flex">
    <h1>Produtos</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Posição na exibição</th>
        <th>Nome</th>
        <th>Link</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.position %>º</td>
          <td><%= product.name %></td>
          <td><%= link_to product.href, product.href %></td>
          <td align="right">
            <%= link_to 'editar', edit_admin_product_path(product), class: 'btn btn-outline-info btn-sm' %>
            <span>&nbsp;</span>
            <%= link_to 'excluir', admin_product_path(product), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to 'Novo produto', new_admin_product_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container pt-4">
  <div class="d-flex">
    <h1>Novo produto</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <%= render 'form' %>
</div>