config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products', as: :products
  get '/solucoes' => 'static_pages#solutions', as: :solutions
  get '/sobre-nos' => 'static_pages#about_us', as: :about_us
  get '/conteudos' => 'static_pages#content', as: :content
  get '/contato' => 'static_pages#contact'

  get '/solucoes/big-data' => 'solutions#big_data', as: :big_data
  get '/solucoes/business-intelligence-analytics' => 'solutions#bi_analytics', as: :bi_analytics
  get '/solucoes/oncase-labs' => 'solutions#oncase_labs', as: :oncase_labs
  get '/solucoes/inteligencia-artificial' => 'solutions#inteligencia_artificial', as: :inteligencia_artificial

  get '/tecnologias/pentaho' => 'technologies#pentaho', as: :pentaho
  get '/tecnologias/cloudera' => 'technologies#cloudera', as: :cloudera
  get '/tecnologias/mongodb' => 'technologies#mongodb', as: :mongodb

  get '/pages/:slug' => 'pages#show', as: :page

  namespace :admin do
    resources :pages do
      resources :text_contents
      resources :image_contents
      resources :link_contents
    end

    resources :products
    resources :solutions
  end

  get 'subscribers/export' => 'subscribers#export', as: :export_subscribers

  resources :subscribers, only: [:create]
end

app/models/solution.rb
class Solution < ApplicationRecord
  has_attachment :logo, accept: [:jpg, :png, :gif]
end

app/controllers/admin/solutions_controller.rb
module Admin
  class SolutionsController < AdminController
    before_action :set_solution, only: [:edit, :update, :destroy]

    def index
      @solutions = Solution.all.order(position: :asc)
    end

    def new
      @solution = Solution.new
    end

    def create
      @solution = Solution.new(solution_params)

      respond_to do |format|
        if @solution.save
          format.html { redirect_to admin_solutions_path, notice: 'A solução foi criada com sucesso!' }
        else
          format.html { render 'new' }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @solution.update_attributes(solution_params)
          format.html { redirect_to admin_solutions_path, notice: 'A solução foi atualizada com sucesso!' }
        else
          format.html { render 'new' }
        end
      end
    end

    def destroy
      respond_to do |format|
        if @solution.destroy
          format.html { redirect_to admin_solutions_path, notice: 'A solução foi excluída com sucesso!' }
        end
      end 
    end

    private

      def set_solution
        @solution = Solution.find(params[:id])
      end

      def solution_params
        params.require(:solution).permit(:name, :description, :logo, :image_height, :position, :href)
      end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def big_data
    @big_data = Page.find_by_slug('big-data')

    @link = @big_data.link_contents.first

    @text_contents = @big_data.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
    @texto_2 = @text_contents.find_by_slug('texto-2')
    @texto_3 = @text_contents.find_by_slug('texto-3')
    @texto_4 = @text_contents.find_by_slug('texto-4')
    @texto_5 = @text_contents.find_by_slug('texto-5')
    @texto_6 = @text_contents.find_by_slug('texto-6')
    @texto_7 = @text_contents.find_by_slug('texto-7')
    @texto_8 = @text_contents.find_by_slug('texto-8')
    @texto_9 = @text_contents.find_by_slug('texto-9')
    @texto_10 = @text_contents.find_by_slug('texto-10')
    @texto_11 = @text_contents.find_by_slug('texto-11')
    @texto_12 = @text_contents.find_by_slug('texto-12')
    @texto_13 = @text_contents.find_by_slug('texto-13')
    @texto_14 = @text_contents.find_by_slug('texto-14')
    @texto_15 = @text_contents.find_by_slug('texto-15')

    @image_contents = @big_data.image_contents
    @imagem_1 = @image_contents.find_by_slug('imagem-1')
    @imagem_2 = @image_contents.find_by_slug('imagem-2')
    @imagem_3 = @image_contents.find_by_slug('imagem-3')
    @imagem_4 = @image_contents.find_by_slug('imagem-4')
    @imagem_5 = @image_contents.find_by_slug('imagem-5')
    @imagem_6 = @image_contents.find_by_slug('imagem-6')
    @imagem_7 = @image_contents.find_by_slug('imagem-7')
    @imagem_8 = @image_contents.find_by_slug('imagem-8')
    @imagem_9 = @image_contents.find_by_slug('imagem-9')
    @imagem_10 = @image_contents.find_by_slug('imagem-10')
    @imagem_11 = @image_contents.find_by_slug('imagem-11')
  end

  def bi_analytics
    @bi_analytics = Page.find_by_slug('bi-analytics')

    @link = @bi_analytics.link_contents.first

    @text_contents = @bi_analytics.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
    @texto_2 = @text_contents.find_by_slug('texto-2')
    @texto_3 = @text_contents.find_by_slug('texto-3')
    @texto_4 = @text_contents.find_by_slug('texto-4')
    @texto_5 = @text_contents.find_by_slug('texto-5')
    @texto_6 = @text_contents.find_by_slug('texto-6')
    @texto_7 = @text_contents.find_by_slug('texto-7')
    @texto_8 = @text_contents.find_by_slug('texto-8')
    @texto_9 = @text_contents.find_by_slug('texto-9')
    @texto_10 = @text_contents.find_by_slug('texto-10')
    @texto_11 = @text_contents.find_by_slug('texto-11')
    @texto_12 = @text_contents.find_by_slug('texto-12')
    @texto_13 = @text_contents.find_by_slug('texto-13')
    @texto_14 = @text_contents.find_by_slug('texto-14')
    @texto_15 = @text_contents.find_by_slug('texto-15')
    @texto_16 = @text_contents.find_by_slug('texto-16')

    @image_contents = @bi_analytics.image_contents
    @imagem_1 = @image_contents.find_by_slug('imagem-1')
    @imagem_2 = @image_contents.find_by_slug('imagem-2')
    @imagem_3 = @image_contents.find_by_slug('imagem-3')
    @imagem_4 = @image_contents.find_by_slug('imagem-4')
    @imagem_5 = @image_contents.find_by_slug('imagem-5')
    @imagem_6 = @image_contents.find_by_slug('imagem-6')
    @imagem_7 = @image_contents.find_by_slug('imagem-7')
    @imagem_8 = @image_contents.find_by_slug('imagem-8')
    @imagem_9 = @image_contents.find_by_slug('imagem-9')
    @imagem_10 = @image_contents.find_by_slug('imagem-10')
    @imagem_11 = @image_contents.find_by_slug('imagem-11')
    @imagem_12 = @image_contents.find_by_slug('imagem-12')
  end

  def inteligencia_artificial
    @inteligencia_artificial = Page.find_by_slug('inteligencia-artificial')

    @link = @inteligencia_artificial.link_contents.first

    @text_contents = @inteligencia_artificial.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
    @texto_2 = @text_contents.find_by_slug('texto-2')
    @texto_3 = @text_contents.find_by_slug('texto-3')
    @texto_4 = @text_contents.find_by_slug('texto-4')
    @texto_5 = @text_contents.find_by_slug('texto-5')
    @texto_6 = @text_contents.find_by_slug('texto-6')
    @texto_7 = @text_contents.find_by_slug('texto-7')
    @texto_8 = @text_contents.find_by_slug('texto-8')
    @texto_9 = @text_contents.find_by_slug('texto-9')
    @texto_10 = @text_contents.find_by_slug('texto-10')
    @texto_11 = @text_contents.find_by_slug('texto-11')
    @texto_12 = @text_contents.find_by_slug('texto-12')
    @texto_13 = @text_contents.find_by_slug('texto-13')
    @texto_14 = @text_contents.find_by_slug('texto-14')
    @texto_15 = @text_contents.find_by_slug('texto-15')
    @texto_16 = @text_contents.find_by_slug('texto-16')

    @image_contents = @inteligencia_artificial.image_contents
    @imagem_1 = @image_contents.find_by_slug('imagem-1')
    @imagem_2 = @image_contents.find_by_slug('imagem-2')
    @imagem_3 = @image_contents.find_by_slug('imagem-3')
    @imagem_4 = @image_contents.find_by_slug('imagem-4')
    @imagem_5 = @image_contents.find_by_slug('imagem-5')
    @imagem_6 = @image_contents.find_by_slug('imagem-6')
    @imagem_7 = @image_contents.find_by_slug('imagem-7')
    @imagem_8 = @image_contents.find_by_slug('imagem-8')
    @imagem_9 = @image_contents.find_by_slug('imagem-9')
    @imagem_10 = @image_contents.find_by_slug('imagem-10')
    @imagem_11 = @image_contents.find_by_slug('imagem-11')
    @imagem_12 = @image_contents.find_by_slug('imagem-12')
  end

  def oncase_labs
    @oncase_labs = Page.find_by_slug('oncase-labs')

    @link = @oncase_labs.link_contents.first

    @text_contents = @oncase_labs.text_contents
    @texto_1 = @text_contents.find_by_slug('texto-1')
    @texto_2 = @text_contents.find_by_slug('texto-2')
    @texto_3 = @text_contents.find_by_slug('texto-3')
    @texto_4 = @text_contents.find_by_slug('texto-4')
    @texto_5 = @text_contents.find_by_slug('texto-5')
    @texto_6 = @text_contents.find_by_slug('texto-6')
    @texto_7 = @text_contents.find_by_slug('texto-7')
    @texto_8 = @text_contents.find_by_slug('texto-8')
    @texto_9 = @text_contents.find_by_slug('texto-9')
    @texto_10 = @text_contents.find_by_slug('texto-10')
    @texto_11 = @text_contents.find_by_slug('texto-11')

    @image_contents = @oncase_labs.image_contents
    @imagem_1 = @image_contents.find_by_slug('imagem-1')
    @imagem_2 = @image_contents.find_by_slug('imagem-2')
    @imagem_3 = @image_contents.find_by_slug('imagem-3')
    @imagem_4 = @image_contents.find_by_slug('imagem-4')
    @imagem_5 = @image_contents.find_by_slug('imagem-5')
    @imagem_6 = @image_contents.find_by_slug('imagem-6')
    @imagem_7 = @image_contents.find_by_slug('imagem-7')
    @imagem_8 = @image_contents.find_by_slug('imagem-8')
    @imagem_9 = @image_contents.find_by_slug('imagem-9')
  end
end

app/views/admin/solutions/_form.html.erb
<%= form_for [:admin, @solution] do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :position, 'Posição na exibição' %>
        <%= f.number_field :position, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :href, 'Link' %>
        <%= f.text_field :href, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :description, 'Descrição' %>
        <%= f.text_area :description %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-body">
          <div class="form-group">
            <%= f.label :logo %>
            <br>
            <%= f.attachinary_file_field :logo, required: true %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :image_height, 'Altura da logo' %>
        <%= f.number_field :image_height, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="actions pt-2">
    <%= f.submit 'Salvar solução', class: 'btn btn-success' %>
    <span>&nbsp;</span>
    <%= link_to 'Cancelar', admin_solutions_path, class: 'btn btn-outline-danger' %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    var simplemde = new SimpleMDE();
  });
</script>

app/views/admin/solutions/edit.html.erb
<div class="container pt-4">
  <div class="d-flex">
    <h1>Editar solução</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <%= render 'form' %>
</div>

app/views/admin/solutions/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <div class="container">
      Tudo certo! <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="container pt-4">
  <div class="d-flex">
    <h1>Soluções</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Posição na exibição</th>
        <th>Nome</th>
        <th>Link</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% @solutions.each do |solution| %>
        <tr>
          <td><%= solution.position %>º</td>
          <td><%= solution.name %></td>
          <td><%= link_to solution.href, solution.href %></td>
          <td align="right">
            <%= link_to 'editar', edit_admin_solution_path(solution), class: 'btn btn-outline-info btn-sm' %>
            <span>&nbsp;</span>
            <%= link_to 'excluir', admin_solution_path(solution), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to 'Nova solução', new_admin_solution_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/solutions/new.html.erb
<div class="container pt-4">
  <div class="d-flex">
    <h1>Nova solução</h1>
    <div class="ml-auto align-self-center">
      <%= link_to 'Voltar ao site', root_path, class: 'btn btn-outline-info' %>
    </div>
  </div>
  <hr class="divider">

  <%= render 'form' %>
</div>