config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products', as: :products
  get '/solucoes' => 'static_pages#solutions', as: :solutions
  get '/sobre-nos' => 'static_pages#about_us', as: :about_us
  get '/conteudos' => 'static_pages#content', as: :content
  get '/contato' => 'static_pages#contact'

  get '/solucoes/big-data' => 'solutions#big_data', as: :big_data
  get '/solucoes/business-intelligence-analytics' => 'solutions#bi_analytics', as: :bi_analytics
  get '/solucoes/oncase-labs' => 'solutions#oncase_labs', as: :oncase_labs
  get '/solucoes/inteligencia-artificial' => 'solutions#inteligencia_artificial', as: :inteligencia_artificial

  get '/tecnologias/pentaho' => 'technologies#pentaho', as: :pentaho
  get '/tecnologias/cloudera' => 'technologies#cloudera', as: :cloudera
  get '/tecnologias/mongodb' => 'technologies#mongodb', as: :mongodb

  get '/pages/:slug' => 'pages#show', as: :page

  namespace :admin do
    resources :pages do
      resources :text_contents
      resources :image_contents
      resources :link_contents
    end

    resources :products
    resources :solutions
  end

  get 'subscribers/export' => 'subscribers#export', as: :export_subscribers

  resources :subscribers, only: [:create]
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  require 'csv'

  def self.to_csv
    attributes = %w{id email}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |subscriber|
        csv << attributes.map{ |attr| subscriber.send(attr) }
      end
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :authenticate_user!, except: :create
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.js
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def export
    send_data Subscriber.to_csv, filename: "subscribers-#{Date.today}.csv"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_with(model: subscriber, local: true) do |form| %>
  <% if subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :subscriber_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribers/create.js.erb
$("input#email").val('');
alert("Você receberá as novidades por email :)");

app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>
  
  <% if @subscribers.empty? %>
    <div class="alert alert-info">
      Não há subscribers.
    </div>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @subscribers.each do |subscriber| %>
          <tr>
            <td><%= subscriber.email %></td>
            <td><%= link_to 'Excluir', subscriber, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to "Exportar", subscribers_export_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>